### ISSUE TITLE
Notify that a user comes online

### ISSUE THREAD

**Issue by Coderlane** [whyrusleeping/GoLiathChat#2]
I would like to know when people I'm waiting to come online come online. Implementation is up to you.

**Comment by whyrusleeping** [comment]
Ill look into cross platform notifications, in gnome its pretty easy, but I haven't looked elsewhere

**Comment by Coderlane** [comment]
I know chrome has one built in, but it isn't as pretty. I also don't know if that is just chrome and not all webkit browsers.I can look around for something that may be useful.
